branches:
  except:
  - gh-pages
  
language: r

cache: packages

r:
  - release

before_script:
  - R -e "install.packages('knitr')"
  - R -e "install.packages('roxygen2')"
  - R -e "install.packages('devtools')"
  - R -e "devtools::install_version('DDIwR', version = '0.2-0')"
  - Rscript -e 'devtools::install()'
  
script:
  - R -e 'devtools::document()'
  - R CMD build .
  - R CMD check *tar.gz
  
after_success:
  - R -e "install.packages('pkgdown')"
  - Rscript -e 'pkgdown::build_site(run_dont_run = TRUE)'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  target_branch: gh-pages
  on:
    branch: master