# safelist
branches:
  only:
  - travis-fixes
  
language: r

cache: packages

r:
  - release

before_script:
  - R -e "install.packages('knitr')"
  - R -e "install.packages('roxygen2')"
  - R -e "install.packages('devtools')"
  
script:
  - R -e 'devtools::document()'
  - R CMD build .
  - R CMD check *tar.gz
  
after_success:
  - R -e "install.packages('pkgdown')"
  - Rscript -e 'pkgdown::build_site(run_dont_run = TRUE)'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on:
    target_branch: travis-fixes-pages