---
title: "Workflow overview"
output: 
  rmarkdown::html_document:
    toc: true 
    toc_depth: 3
    number_sections: false  
pkgdown:
  as_is: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
## Introduction
**bllFlow** uses seven steps to develop predictive algorithms. The steps 
emphasize a _pre-specified_ approach following Harrell, Styerberg and others. 
_Pre-specified_ means the predictive model is specified prior to examining the 
relationship between predictors (also known as risk factors or features) and the 
outcome (target). 

### Step 1 - Specifying your model
The model specifications are recorded within the Model Specification Worksheet 
(MSW). Each predictor in your model is a row in the MSW. Included are columns 
for variable labels, data cleaning, variable transformation rules and other 
instructions that can be rountinely-performed (Step 4).

Creating the MSW invovles everyone on your team: analysts, methodologist and
content experts. Trainees will want to review their MSW with their supervisor 
and thesis committee. 

### Step 2 - Describing the study cohort
Research studies tyipically include a "Table 1" that describe the study cohort 
or population. This step creates a CSV file with the all infomation required for 
Table 1 and also similar descriptive tables and codebooks. **bllFlow** follows 
the [Data Documentation Intitiatve](https://www.ddialliance.org) concept of "one 
document, many uses."

**bllFlow** steps are sequential, but there is room a small amount if iteration, 
particularly for Step 2. For example, most research reporting guidelines 
recommended a description of the study cohort before any data cleaning to 
disclose and communicate data quality (amount of missing data, etc.). It is 
helpful to also description of your study data after data cleaning, 
and variable transformation (Step 3).

### Step 3 - Data cleaning and variable transformation
Data cleaning and varible transformation is the most time consuming step of 
model development -- and also a step that poorly communicated and difficult 
to reproduce. **bllFlow** strives to reduce the effort required in this 
step as much as possible, while also improving transparency and reproduciblity. 

### Step 4 - Developing a predicitve model
This step is short and breif for **bllFlow**. **bllFlow**
 doesn't contain any functions for actual statistical or machine learning models.
 Rather, **bllFlow** acts more like a wrapper around the model model derivation, 
 by providing help prior to and following actual model development. You bring 
 your own model functions. 
 
 A challenge when using different modelling packages and software programs 
 are different approaches to variable transformation that occurres within model 
 generation. For example, dummy variables can be created, but using different 
 naming conventions.
 
### Step 5 - Reporting the performance of a model
 
### Reference files - Variable types, labels and metadata
**bllFlow** uses consistent labels and metadata throughout the workflow. The 
`variable-metadata` file is a table that identifies all variable types used. For 
example, `mean`  refers to the mean value of an exposure. All variable types are 
defined to ensure consistent, understandable and machine-actionable across 
software libraries.

### Helper and utility functions

