---
title: "1 - Specifying your model"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{1 - Specifying your model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
## Introduction

The Model Specification Workbook (MSW) is the central document creating your 
model using _bllflow_. 
Worksheets within the MSW contain both the names of the starting variables in the original study 
data and the final variables, if variable are transformed. 

There are two approaches to creating the MSW. We usually start the MSW as a CSV 
file to facilate collaboration -- and this approached is used throughout the 
vignettes. Alternatively, you can create the MSW as an R dataframe. 

The first step in _bllflow_ is to identify all starting and final variables for 
your model in the MSW. We emphasize pre-specified analyses but 
variables can be added as you perform study. We highly recommend any additional 
variables and transformation be added to the MSW to ensure reproducibilty and 
transparency. The MSW is a record of how you created your model and what analyses
 you performed. As well, _bllflow_ uses metadata throughout the workflow. 

The second step is to add variable labels and other metadata to the MSW that 
provides instructions for data cleaing and transformation. 

*bllFlow* supports importing metadata from:

- DDI (xml) documents;
- variable lablels in study dataframe as `attr` label (using hmisc, sjlabelled or
similar packages); or,
- manually added added to the MSW.

## Worksheets 
**bblFlow** has four worksheets within the MSW:

1) `modelDescription` --- the name of the model, date created and other 
information about the study.
1) `variables` --- all model variables, including data cleaning and 
transformations. 
1) `variableDetails` --- information on factors (categories) and how to transform
 final variables from their starting variables. 
1) `summaryVariables` -- variables that are used in model reporting, such as 
for `Table 1`. 

```
# pbc data for examples and vignettes
library(survival)
data(pbc)

Read in the MSW and variable_details sheet for the PBC model
modelDescription <- read.csv(file.path(getwd(),..
variables <- read.csv(file.path(getwd(), 'bllFlow/extdata/PBC/PBC - variables.csv'))
variableDetails <- read.csv(file.path(getwd(), 'bllFlow/extdata/PBC/PBC - variable_details.csv'))

# Create a bllFlow R object for the PBC model using the above variables as args
library(bllFlow)
pbcModel <- BLLFlow(pbc, variablesSheet, variableDetailsSheet)
```