---
title: "Introduction to bllFlow"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to bllFlow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
The [`Workflow`](a_workflow.html) menu describes seven steps when performing 
research using observational data. You can pick and choose to use any steps that 
fit your workflow.

There there are three distictive features of **bllFlow**:

- **The Model Specification Workbook (MSW)** - CSV files that contain key 
information (metadata) about your data, model, the variables in your model, data
cleaning and transformation steps and how to create output tables. 

- **Functions to perform rountine data cleaning and transformation tasks** - 
bllFlow functions uses the MSW as instructions perform common tasks. (example here...)
For example, `bllFlow.center(data)` centers all variables in the MSW where 
center == TRUE, then creates a new variable with the `_c` suffix and logs which 
variables are centred. 

- **Formatted output files, tables** - CSV files that contain results of 
your model that adhere to reporting guidelines such as [TRIPOD](https://www.equator-network.org/2015/01/07/guidelines-for-reporting-multivariable-prediction-models-for-individual-prognosis-or-diagnosis-tripod-published/), [STROBE](http://www.equator-network.org/reporting-guidelines/strobe/), and [RECORD](http://www.equator-network.org/reporting-guidelines/record/).

At any point of your analyses you:

- always have labels for variables.
- have a log data cleaning and transformed variables (how your data has 
been cleaned and transformed).
- have a complete codebook, with information with data provenance of all variables.

For predictive algorithms, **bllFlow** generates Predictive Model Modelling Language ([PMML](http://dmg.org/pmml/v4-3/GeneralStructure.html)) files for algoirithm delployment. 
