---
title: "Recode of the recipe test"
author: "Rostyslav Vyuha"
date: "August 20, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

First the simple dataset creation make sure that the column u want to work with is a numeric

```{r}
mockData <- data.frame(foo = c(NA, 1, 1, 6), bar = c(3, 4, 6, NA), ter = c(12, NA, 20, 9))

```

Then we create our recipy with the mock data

```{r}
library(recipes)
library(bllflow)
testRecipy <- recipe(foo ~., data = mockData)

```

Now we can add the standard meanimpute call but with my function

```{r}
testRecipy <- step_meanimpute(testRecipy, bar)
testRecipy <- step_meantest(testRecipy, ter)
testObj <- prep(testRecipy, training = mockData)
testOut <- bake(testObj, new_data  = mockData)
print(testOut)
```

Now for custom suffix and appending to the original variable

```{r}
testRecipy <- recipe(foo ~., data = mockData)
testRecipy <- step_meantest(testRecipy, ter, bar, suffix = "_TheTestIsWorking", append = TRUE)
testObj <- prep(testRecipy, training = mockData)
testOut <- bake(testObj, new_data  = mockData)
print(testOut)
```