SetAllColumnsToChars <- function(passedTable){
  passedTable <- data.frame(lapply(passedTable, as.character))
  return(passedTable)
}
library(bllflow)
library(survival)
ddi <- list()
data(pbc)
variables <- read.csv(system.file("extdata/testdata", "PBC-variables.csv", package = "bllflow"))
newVariables <- read.csv(system.file("extdata/testdata", "PBC-variablesUpdateTest.csv", package = "bllflow"))
variableDetails <- read.csv(system.file("extdata/testdata", "PBC-variableDetails.csv", package = "bllflow"))
ddiVariableDetails <- read.csv(system.file("extdata/testdata", "ddiPopVariableDetails.csv", package = "bllflow"))
newVariableDetails <- read.csv(system.file("extdata/testdata", "PBC-variableDetailsUpdateTest.csv", package = "bllflow"))
catVars <- c("status", "trt", "ascites", "hepato", "spiders", "edema", "stage")
TableOne1 <- CreateTableOne(data = pbc,strata = c("trt"), factorVars = catVars)
TableOne2 <- CreateTableOne(data = pbc,strata = c("trt","stage"), factorVars = catVars)
LongTableNoLabelStandards <- read.csv(system.file("extdata/testdata", "CompareLongTable.csv", package = "bllflow"), as.is = TRUE)
LongTableNoLabelStandards <- SetAllColumnsToChars(LongTableNoLabelStandards)
LongTableLabelStandards <- read.csv(system.file("extdata/testdata", "CompareLongTableWithLabels.csv", package = "bllflow"), as.is = TRUE)
LongTableLabelStandards <- SetAllColumnsToChars(LongTableLabelStandards)
AppendedLongTableNoLabelStandard <- read.csv(system.file("extdata/testdata", "CompareAppendedLongTable.csv", package = "bllflow"), as.is = TRUE)
AppendedLongTableNoLabelStandard <- SetAllColumnsToChars(AppendedLongTableNoLabelStandard)
AppendedLongTableLabelStandard <- read.csv(system.file("extdata/testdata", "CompareAppendedLongTableWithLabels.csv", package = "bllflow"), as.is = TRUE)
AppendedLongTableLabelStandard <- SetAllColumnsToChars(AppendedLongTableLabelStandard)
load(system.file("extdata/testdata", "ddiInfo.Rdata", package = "bllflow"))
model <- BLLFlow(pbc, variables, variableDetails,ddi)
