context("SummaryDataLong")
library(bllflow)

test_that("SummaryDataLong converts tableOne into a long table", {
  
})
test_that("SummaryDataLong appends tableOne to passed long table", {
  
})
test_that("SummaryDataLong append tableOne to passed long table as well as labels from bllFlow object", {
  
})
test_that("SummaryDataLong converts tableOne into a long table with labels from bllFlow object", {

})
test_that("SummaryDataLong throws an error when an invalid tableOne is passed", {
  #Invalid tableOne was passed please use the tableone package to create the tableone 
})
test_that("SummaryDataLong throws an error when an invalid long table is passed", {
 #Invalid summary Table was passed please make sure it is generated by SummaryDataLong
})
test_that("SummaryDataLong throws a warning when bllFlow object does not contain DDI", {
  #The passed bllFlow Object does not contain ddi labels no labels were attached to long table
})



